### ISSUE TITLE
Hide a manufacturer from view

### ISSUE THREAD

**Issue by andymnewhouse** [cherryaudio/store-issues#1]
### Description:

Ability to hide a manufacturer from the store, both on the web and inside Voltage Modular

**Comment by andymnewhouse** [comment]
1. default to checking all manufacturers.
2. add 'all' and 'none' buttons at top.
3. remember settings for future sessions

**Comment by andymnewhouse** [comment]
![image](https://user-images.githubusercontent.com/6541180/113164668-eab32480-9206-11eb-846f-adba25ad580e.png)

Idea for implementation

**Comment by nekomatic** [comment]
With the approach above there is a risk new manufacturer's modules may be by default invisible. 
Would't be better to control what the 'tick' means? i.e. As a shop visitor I want to be able to set 'visibility settings' which control if ticking a box next to a manufacturer means either:
A. hide only modules from the the ticked manufactutrers
B. show only modules from the ticked manufactutrers
the default state would be the the A. and nothing ticked
wne new manufacturer appears for the firts time it's 'ticked' state should make their modules visible as per the current visibility settings

**Comment by andymnewhouse** [comment]
Yeah I don't want to make new manufacturer's invisible by default! 

I was planning on only saving the Manufacturers that are "hidden". 

Maybe instead of a checkbox I could change the control to a toggle so it's a little more clear what's visible and not. What do you think?

**Comment by nekomatic** [comment]
Yes, a 'visible/invisible' toggle would be much better. New manufacturers would be 'visible' by default.

**Comment by andymnewhouse** [comment]
![toggle-mockup](https://user-images.githubusercontent.com/6541180/113172176-cd358900-920d-11eb-9587-72cf2b09c0e1.png)

Here's a quick mockup, I'd give each manufacturer a little more breathing room cause the toggles are a little squished right now.

**Comment by andymnewhouse** [comment]
I do think quick toggles to turn all on/off would be helpful. What do you think?

**Comment by nekomatic** [comment]
Looks reasonable to me
