### ISSUE TITLE
Can't enter a percentage value for promotions

### ISSUE THREAD

**Issue by gregbir** [cherryaudio/store-issues#100]
From the user forums:

Hi,
at the moment I'm preparing for holiday sales. Therefore I want to edit a promotion, that I defined last year.
Instead of a former manually set discount price I want to set a percentage now. New discount price changes, when I enter percentage value.
But the new price cannot be seen in promotion details, although I clicked on SAVE button. Even when I reload browser page, formerly set discount will be shown.
Did I do something wrong?
Any hint is welcome.
-----
I want to add an information.
When I open promotion details for an edited product again, entered percentage value has disappeared. Former manually set sales price is still there.
https://forums.cherryaudio.com/viewtopic.php?f=11&t=1980

**Comment by techenby** [comment]
Fixed in 3.7.0
