### ISSUE TITLE
FR: Indicate which promotions are official Cherry promotions

### ISSUE THREAD

**Issue by tstone** [cherryaudio/store-issues#101]
### Description:

I see there is now a shared promotion feature. I think it would be good if there was something to indicate (an icon maybe?) that a promotion was an official Cherry Audio promotion.

**Comment by techenby** [comment]
Yup! That’s on my Monday morning todo list along with deleting promotions :)

**Comment by tstone** [comment]
This appears to have been added with the holiday promotion a few months ago. Closing.
