### ISSUE TITLE
Categories not being recognised for some products (at least on preview page)

### ISSUE THREAD

**Issue by TheAndyMac** [cherryaudio/store-issues#102]
Browser Report:  https://www.whatsmybrowser.org/b/I07IT

### Description:
Some new products added to the store don't show up their category on the Products page although the category has been set correctly in the module and is being shown in the product page itself -- seems mainly to be the Utility category but can't be sure. Also, for Utility category items, the preview tab does not show any Category. MAYBE a mismatch between "Utilities" as selected in Module Designer and "Utility" as listed in the store?

### Detailed steps to reproduce the issue:
Create a new module with category Utilities and publish it. Go to the Products list page - the module will be listed but the category will be blank. Edit module description, etc. and "Utility" will be shown in the drop down BUT once saved, will show nothing on the preview tab.

**Comment by TheAndyMac** [comment]
Looks like this might have been resolved somehow - they now seem OK. Maybe a background task updating stuff?

**Comment by scottmetoyer** [comment]
Fixed in 3.8.17
