### ISSUE TITLE
Pricing and availability tab - needs a value in demo length even if demo not allowed

### ISSUE THREAD

**Issue by TheAndyMac** [cherryaudio/store-issues#103]
Browser Report: https://www.whatsmybrowser.org/b/I07IT

### Description:
When changing price but not allowing demo, the pricing and availability tab does not allow you to proceed if there is no value in the demo length - workaround is to set to 0, but a bit annoying

### Detailed steps to reproduce the issue:
Create new module (and publish it) or new bundle. Go to pricing and availability. Change price to something. Try to save - comes up with error showing demo length as requiring a value even though demo is set to not available.

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/12783814/147254738-0d640b35-f6e0-41b5-8103-b8433e53cd7f.png">

**Comment by techenby** [comment]
Fixed in 3.8.1 - will hopefully be published this week or early next.
