### ISSUE TITLE
Multiple Manufacturers Link from VMD

### ISSUE THREAD

**Issue by tstone** [cherryaudio/store-issues#104]
Say I have 2 manufacturer accounts, A and B.

If I open manufacturer B in the dashboard, it remembers it. If I then publish a module from VMD to manufacturer A, and click the link presented in VMD after publish, it takes me to the page for the module, but showing in the context of manufacturer B even though I published it to A.

**Comment by techenby** [comment]
Fixed in 3.8.3

**Comment by techenby** [comment]
3.8.3 Has been released
