### ISSUE TITLE
Build #1 does not show category on product index view

### ISSUE THREAD

**Issue by tstone** [cherryaudio/store-issues#105]
### Description:
In the products index view in Nebula (https://store.cherryaudio.com/nebula/products), Build #1 does not show the "CATEGORY" in the table view.

### Detailed steps to reproduce the issue:

1. Create a module in VMD and set a category 
2. Publish the first build
3. Open https://store.cherryaudio.com/nebula/products
4. "CATEGORY" column is blank, despite it being set on the module

It seems that publishing a 2nd build populates the category value correctly.

**Comment by scottmetoyer** [comment]
Fixed in 3.8.17

**Comment by scottmetoyer** [comment]
I've deployed a fix that should address this. Can you take a look when you have a moment and verify everything checks out? Thanks!
