### ISSUE TITLE
Voltage Modular Software can be added to user library without modules or presets

### ISSUE THREAD

**Issue by cherryLutz** [cherryaudio/store-issues#106]
Browser Report:  _https://www.whatsmybrowser.org/b/YLSUK_

### Description:
If a customer wants Voltage Modular and somehow ends up on [this page](https://store.cherryaudio.com/bundles/voltage-modular-software), they can add the Voltage Modular Software to their library without any bundled presets or modules. Ideally, we hide this page, or if they choose to **Add to Library**, it redirects them to the bundles page where they choose which of the three bundles they want.

**Comment by scottmetoyer** [comment]
I've hidden the bundle from the store. Note that this can be done in Nebula by checking the 'hide in store' checkbox on the Pricing and Availability tab of the Voltage Modular Software bundle.
