### ISSUE TITLE
Link YouTube accounts to manufacturers or products

### ISSUE THREAD

**Issue by andymnewhouse** [cherryaudio/store-issues#11]
### Description:

I have a matching YouTube account, with videos all about the modules I’m selling and other VM tips. Having that bit a bit more obvious would be nice, especially on the product page where I feel seeing a video demo is an aid to selling.

**Comment by tstone** [comment]
To be clear, this was a bug. If you look below the "m" in the header where the YouTube icon should be, you'll see it's a rotating !/? icon instead. https://store.cherryaudio.com/manufacturers/collider-modular
