### ISSUE TITLE
Sales Report Download Broken

### ISSUE THREAD

**Issue by TheAndyMac** [cherryaudio/store-issues#110]
Browser Report:  [Edge 103](https://www.whatsmybrowser.org/b/U9AQ1)

### Description:
I am trying to download the complete report of sales on your system https://store.cherryaudio.com/nebula/sales-reports but when I request the download it comes up with an error 500, server error. If I select 10 items at a time it seems to be OK.

### Detailed steps to reproduce the issue:
1. Go to Sales Reports https://store.cherryaudio.com/nebula/sales-reports
2. Set list to 100
3. Select all entries
4. Confirm that want all (which in my case is 40)
5. Select DOWNLOAD
6. A few seconds later comes up with Error 500 page

If I select 10 at a time (leave as 10 per page rather than accepting the "select all" prompt, select page, download, clear, next page...) then each set of 10 gets downloaded OK.

**Comment by scottmetoyer** [comment]
Fixed in upcoming release 3.10.5

**Comment by scottmetoyer** [comment]
This issue has been fixed in production. You should find the sales reports significantly more performant now. Thanks for reporting!
