### ISSUE TITLE
Submit multiple modules/bundles list does not scroll

### ISSUE THREAD

**Issue by TheAndyMac** [cherryaudio/store-issues#111]
Browser Report:  https://www.whatsmybrowser.org/b/U9AQ1

### Description:
List of multiple items to submit on product page does not scroll - can't submit more than 20 or so as can't get to submit button

### Detailed steps to reproduce the issue:
Multiple module updates to be submitted. Select all (say 100). List comes up OK but can't get to submit button. The list should allow vertical scrolling of the modules/bundles in the list with the text box and submit button always visible.

**Comment by scottmetoyer** [comment]
Fixed in upcoming release 3.10.5

**Comment by scottmetoyer** [comment]
This issue has been fixed in production by adding the scrollbar as you suggested. Thanks for reporting!

**Comment by TheAndyMac** [comment]
Thank you – that’s a big help 😊

Regards
Andrew Macaulay

**Comment by TheAndyMac** [comment]
Thanks 👍👍

Regards
Andrew Macaulay
