### ISSUE TITLE
Promotion Settings: Time Zones

### ISSUE THREAD

**Issue by TheAndyMac** [cherryaudio/store-issues#112]
Browser Report:  https://www.whatsmybrowser.org/b/QNIXV

### Description:

1. Time zone list is not showing city/country information
2. Time zone for London does not reflect British Summer Time

### Detailed steps to reproduce the issue:

Copy or start a new promotion
Change timezone in promotion settings - list only shows GMT or GMT+ or GMT-
Once I found (by trial and error) London, find that it had to be set to 17:00 in promotion (today) for it to start at 18:00 UK time

**Comment by scottmetoyer** [comment]
Fixed in release 3.11.13

**Comment by scottmetoyer** [comment]
A fix has been deployed to production. Thanks for reporting this issue!

**Comment by TheAndyMac** [comment]
No problem and thanks

Regards
Andrew Macaulay
