### ISSUE TITLE
Order of images not reflected in carousel

### ISSUE THREAD

**Issue by andymnewhouse** [cherryaudio/store-issues#14]
### Description:

The new dashboard allows images to be re-ordered. It properly saves the order, but that order is not reflected on the preview page.

Reported by: Collider Modular

**Comment by andymnewhouse** [comment]
Fixed in v3.5.6

**Comment by andymnewhouse** [comment]
3.5.6 has been published to the production server.

**Comment by tstone** [comment]
Looking at the latest build now, and I'm noticing a couple things still:

- There are 2 ways to preview a module which give different results. First by going to Product > Preview. Second by going to Product > View Submission.
- On Product > Preview the preview renders just a solid light gray box with no images if the order of images has been changed.
- On Product > View Submission the preview renders without applying the order.

If you want to see an example of this, check out submission 1981 or product 2491, build 23.

**Comment by andymnewhouse** [comment]
Fixed in 3.5.19
