### ISSUE TITLE
Submission comments remain in input box

### ISSUE THREAD

**Issue by tstone** [cherryaudio/store-issues#16]
- Operating System and Version: #.#
- Browser type and version: #.#

### Description:
When replying to a submission, there is a `<textarea> #comment` to enter a response into. Pressing "Save" correctly sends the comment, but the comment remains populated in the <textarea> instead of clearing out after sent.

### Detailed steps to reproduce the issue:

- Open a pending or rejected module submission
- Enter a comment in "New Comment"
- Press "Save"
- Comment posts but remains filled in textarea

**Comment by andymnewhouse** [comment]
Fixed in 3.5.7
