### ISSUE TITLE
Nebula: Manual Upgrade Prices List does not show newly added (not yet approved) items

### ISSUE THREAD

**Issue by TheAndyMac** [cherryaudio/store-issues#19]
### Description:
If you are adding new modules and want to include discounts for cross-module or manual upgrade pricing to collections, the new modules (at least when not approved) do not show. This means that any setup will need a follow on stage after approval to setup the manual discounts.

### Detailed steps to reproduce the issue:
Add a new product. Try to add the product into a Manual Upgrade pricing - they do not show.

**Comment by andymnewhouse** [comment]
Fixed in 3.6.0
