### ISSUE TITLE
Updating Icon media in new build of Bundle not shown on Preview

### ISSUE THREAD

**Issue by TheAndyMac** [cherryaudio/store-issues#20]
### Description:
If you change the icon on a new build of an existing Bundle (and make sure it saves), the Preview still shows the old icon.

### Detailed steps to reproduce the issue:
Add a build to an existing Bundle. Replace the icon in the Media tab. Preview the new build.

**Comment by andymnewhouse** [comment]
Is the previous build published? I'm guessing it's grabbing that icon instead which should be an easy enough fix.

**Comment by TheAndyMac** [comment]
Yes it was - not seen this issue recently, so don't know if already fixed - and not got any new builds coming up at present, so can't test myself.

Regards
Andrew Macaulay

**Comment by andymnewhouse** [comment]
Cool, I'll see if I can repro!

**Comment by andymnewhouse** [comment]
I wasn't able to reproduce, but I've also changed the preview image code so that might have fixed it. So I'm going to close this for now, but if you see it again feel free to open it up again!

**Comment by TheAndyMac** [comment]
Thanks

Regards
Andrew Macaulay

________________________________
