### ISSUE TITLE
Confirmation email for invitation to dev/beta team goes to old manu interface

### ISSUE THREAD

**Issue by soundwarrior** [cherryaudio/store-issues#23]

**Comment by andymnewhouse** [comment]
I've tested the beta flow and it works as expected. Beta users are not allowed access to Nebula or the old Dashboard.

**Comment by andymnewhouse** [comment]
Can confirm that inviting to dev team redirects to the old dashboard instead of Nebula.

**Comment by andymnewhouse** [comment]
Fixed in 3.5.19
