### ISSUE TITLE
Need to see reason why something was rejected in Nebula

### ISSUE THREAD

**Issue by soundwarrior** [cherryaudio/store-issues#25]

**Comment by soundwarrior** [comment]
Also in Galaxy, there is no way that I can see to see the submission history.  And don't forget the hyperlinks on the product name, etc.

**Comment by andymnewhouse** [comment]
In nebula did you scroll down? It should be on the bottom of the page. But I could reverse the order.

**Comment by andymnewhouse** [comment]
Fixed in 3.5.10
