### ISSUE TITLE
Searching in products in Nebula is not working for unpublished modules.

### ISSUE THREAD

**Issue by soundwarrior** [cherryaudio/store-issues#27]
### Detailed steps to reproduce the issue:
1. Go to Nebula.
2. Search on 'piano'
3. ==> nothing shows up.

**Comment by soundwarrior** [comment]
I put Piano Roll in beta and now it shows in the search.  I cannot find Reanimator though. (It's not in beta.)

**Comment by andymnewhouse** [comment]
I believe this has been fixed, can you check?

**Comment by andymnewhouse** [comment]
Was kinda sorta fixed, but still need to fill in product name and slug from current builds where product info is still null
