### ISSUE TITLE
Show percentage of bundle owned as progress bar

### ISSUE THREAD

**Issue by andymnewhouse** [cherryaudio/store-issues#28]
### Description:

Show percentage of bundle owned as progress bar under the image.

<img width="309" alt="Screen Shot 2021-03-12 at 11 40 26 AM" src="https://user-images.githubusercontent.com/6541180/110977659-0a51de00-8328-11eb-9723-53d7236dfda3.png">

**Comment by WeevilAudio** [comment]
If you work on this I think it would be a good idea to tweak how bundle discounts work. My preference is to allow a percent discount based on what you already own, either automatic based on the value of the modules you own or completely configurable by the developer.

Auto should (in my opinion) work like this:

Module A - 20
Module B - 10
Module C - 30

Bundle with A, B and C - 40

If I own module C, I own 50% of the bundle, so bundle price would be:
40 * (60 - 30) / 60 = 20

If I own module B the bundle price would be:
40 * (60 - 10) / 60 = 33.33

**Comment by andymnewhouse** [comment]
Actually that's exactly how the automatic discount works!

**Comment by WeevilAudio** [comment]
Thats great, has this changed recently or has it always worked like this? I had problems with bundles before but that might just have been during sales.

Does the same discount apply when there is a sale on the bundle?

**Comment by andymnewhouse** [comment]
It's a new addition in Nebula, you can enable it on the Pricing tab of a product.

Right now it doesn't also apply that discount when a sale is active which is an oversight.

**Comment by andymnewhouse** [comment]
I've created a new bug where you can follow that issue: #55

**Comment by andymnewhouse** [comment]
Added in 3.5.21

**Comment by WeevilAudio** [comment]
Great, thanks!
