### ISSUE TITLE
VMDesigner links to old version

### ISSUE THREAD

**Issue by tstone** [cherryaudio/store-issues#34]
### Description:
The link generated in VMDesigner after publishing a build links to the previous version. For example, if the current latest build is 8, and a new build is published, making it build 9, the link in the dialog after publishing links to build 8.

### Detailed steps to reproduce the issue:

- Open a module in VMDesigner
- Build > Publish
- Click link in dialog after publish
- It's one version old

**Comment by andymnewhouse** [comment]
Fixed in 3.6.0
