### ISSUE TITLE
Change Pay to Confirm after PayPal account selected

### ISSUE THREAD

**Issue by techenby** [cherryaudio/store-issues#42]
### Description:

They click the paypal purchase button and confirm what their Paypal account is that they need to purchase with.

Then they are returned to the purchase page and they think that they have completed the purchae. But they have not.  They need to click the same purchase button a second time to complete the purchase. They think that they are going to be charged two times so they are hesitant.

I was thinking the buttton name should change the second time.  The first time the button could be "Paypal" and the second time it could say "confirm"

**Comment by scottmetoyer** [comment]
Fixed in 3.9.3

**Comment by scottmetoyer** [comment]
Deployed to production.
