### ISSUE TITLE
Published modue does not appear in the store

### ISSUE THREAD

**Issue by nekomatic** [cherryaudio/store-issues#44]
Published modue does not appear in the store

**What Happened**
I have published a module yesterday but it is not visible in the store. I do remember it could take up to an hour or so in the past. 
The link provided by the panel is https://store.cherryaudio.com/modules/micro-spectro-scope. At this moment the link leads to the error page with the error message **Whoops looks like something got unplugged.**

**Expected behavior**
Module should be descoverable in the store when showing all modules, limiting to 'nekomatic' modules and when using the module link. 

**Screenshots**
Does not depend on browser nor OS

**Additional context**
I'm not sure if it could affect this but at the moment of publishing the module the 'hide in store' option was selected.

**Comment by andymnewhouse** [comment]
Yeah so what happened was "hide_in_store" was set to false, but I think my query just looks for the existence of that key in the settings rather than that key being set to true. I'll get this fixed ASAP.

**Comment by andymnewhouse** [comment]
Fixed in 3.5.19
