### ISSUE TITLE
Issues with adding products to a bundle

### ISSUE THREAD

**Issue by SynthDan** [cherryaudio/store-issues#47]
I'm trying to add 21 VM2500 modules plus the presets to the VM2500 Collection bundle, in the Cherry Audio / MRB manufacturer.

The old interface for this is extremely fast and easy to use:

![image](https://user-images.githubusercontent.com/13699795/113353595-c6347680-92f2-11eb-8868-bcd8d1260918.png)

Whereas the new interface is very, very difficult to use for this purpose:

![image](https://user-images.githubusercontent.com/13699795/113353468-8d949d00-92f2-11eb-9a4e-bfd4a93b330c.png)

1) Products that are already in the bundle still appear in the search results.
2) The search results only show 4 items and are not scrollable, so once I've added the first 4 search results for 'VM2500' there is no way to add additional items without searching for those exact items by name.
3) When there are no items in the bundles, and the first item is added, the list does not update unless you refresh the page.
4) Only a single item can be added at a time via the dropdown.

With the old interface, I can very, very quickly add items by searching for "VM2500" and then just clicking on all the search results. 10 seconds and I'm done. With the new interface, it would take 5 minutes or more to search for every product name, click on it, press the Add button, then repeat the cycle all over again.

**Comment by andymnewhouse** [comment]
Fixed in 3.6.0
