### ISSUE TITLE
New Manufacturers' Filter on Bundles and Modules Store Pages - Manufacturers' Names Not Showing

### ISSUE THREAD

**Issue by TheAndyMac** [cherryaudio/store-issues#49]
Browser Report: Microsoft Edge Version 89.0.774.68 on Windows 10

### Description:

The text for the manufacturers' names appears to be black on a black background - select any line and the text is there, just not visible in normal use.

### Detailed steps to reproduce the issue:
As displayed when open up the store page:
<img width="238" alt="Normal list as displayed" src="https://user-images.githubusercontent.com/12783814/113880165-24f66600-97b3-11eb-8dcc-0dfbcfb3c51b.png">

Click and drag over the first few rows shows the text is there:
<img width="235" alt="Selecting the first few rows by clicking and dragging mouse over them" src="https://user-images.githubusercontent.com/12783814/113880172-26279300-97b3-11eb-8eb3-b4dd9d4edc6c.png">

**Comment by andymnewhouse** [comment]
Can you say more or provide a screenshot?

**Comment by TheAndyMac** [comment]
Have done – I just submitted by mistake before including the details ☹
You should have enough now, hopefully

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by andymnewhouse** [comment]
Oooh gotcha yeah this should be a really easy fix! Give me an hour!

**Comment by andymnewhouse** [comment]
Fixed in 3.5.20
