### ISSUE TITLE
Product is owned in a bundle - still shows 'buy in bundle' when clicking in to product page.

### ISSUE THREAD

**Issue by soundwarrior** [cherryaudio/store-issues#57]
### Detailed steps to reproduce the issue:
1) own the core bundle
2) Search on 'piano' to find the piano roll module.
==> Notice it says it is owned.
3. Click in to the product.  It says that the user can buy in it in a bundle.

![image](https://user-images.githubusercontent.com/679120/114908795-4a95f780-9dd1-11eb-87b6-ca0571775278.png)
![image](https://user-images.githubusercontent.com/679120/114908803-4d90e800-9dd1-11eb-853c-3eb7363ea352.png)

**Comment by andymnewhouse** [comment]
Fixed in 3.6.0
