### ISSUE TITLE
Manufacturers need to be sorted case insensitive

### ISSUE THREAD

**Issue by soundwarrior** [cherryaudio/store-issues#61]
### Description: Go to the bundle page or any page with the devs.  Anthony noticed that the dev 'nekomatic' is at the end of the list...as it is lowercase.

![image](https://user-images.githubusercontent.com/679120/116284398-e6b0ee80-a741-11eb-9506-5222f01b9628.png)

**Comment by andymnewhouse** [comment]
Fixed in 3.5.23
