### ISSUE TITLE
Manual bundle discount items can't be removed after enabling automatic

### ISSUE THREAD

**Issue by tstone** [cherryaudio/store-issues#64]
Browser Report: https://www.whatsmybrowser.org/b/9VDVC

### Description:

I just enabled automatic bundle discounts. Removing the manual discounts that were applied does not work. I click the trashcan icon, it removes, then I hit "save", and it says it saved successfully. Coming back to the page however the manual discounts remain.

**Comment by andymnewhouse** [comment]
It actually wasn't related to the automatic bundle discounts, but it's been fixed for the next release!

**Comment by andymnewhouse** [comment]
Fixed in 3.5.26
