### ISSUE TITLE
Add field and sorting to User's library page

### ISSUE THREAD

**Issue by soundwarrior** [cherryaudio/store-issues#66]
### Description: As the number of products and modules are added, it would be nice to see some sorting abilities in the user product area.  I suggest it defaults to "Most Recent" and should have the following.

* Most Recent
* Type
* Name
* Manufacturer

etc

**Comment by andymnewhouse** [comment]
What page are you talking about?

**Comment by techenby** [comment]
On the users library (https://store.cherryaudio.com/my/settings/library)

Add a date added column and add sorting to both the date added and type.

**Comment by scottmetoyer** [comment]
I think this has been pretty much superseded by the library enhancements I deployed last month (added ecosystem grouping, streamlined search, paging, etc). Can I go ahead and close this out?
