### ISSUE TITLE
All Modules check fail

### ISSUE THREAD

**Issue by cmountvpr** [cherryaudio/store-issues#67]
**Describe the incident**
In Modules view, Categories "All" button fails to check all categories.

**What Happened**
1. Go to 'Modules'.
2. Click on 'None' to clear all.
3. Click on 'All' to check all.
4. CV Processors, Processor and Utility Categories are the only ones that become checked.

**Expected behavior**
All Module Categories should become checked, but they don't.

 - OS: [macOS 10.14]
 - Browser: happens in Safari 14 and Chrome 90

**Additional context**
I've discovered something. After I click Categories 'All' (and experience the problem above) then switch to Bundles view, then back to Modules view, all Categories are correctly selected.

**Comment by techenby** [comment]
Fixed in 3.6.5
