### ISSUE TITLE
Sale badge displayed on items which do not match sale criteria

### ISSUE THREAD

**Issue by nekomatic** [cherryaudio/store-issues#68]
I have a number of items in the store which are set up to be on sale on the condition the user owns a particular other item however the 'SALE' badge is displayed regardless if the item matches the sale conditions or not.

The 'SALE' badge should not be displayed when the item does not match any same conditions.
My suggestions are either:
- do not display the 'SALE' badge is the item's price is not less tha the list price.
or
- do not display the 'SALE' badge is none of the sale conditions evaluate as 'true'.

**Comment by andymnewhouse** [comment]
Fixed in 3.6.0
