### ISSUE TITLE
Edit Deal Promotions Link Incorrect

### ISSUE THREAD

**Issue by tstone** [cherryaudio/store-issues#69]
The "Promotions" link on the left-mode sidebar on the "Edit Deal" page within Nebula incorrectly links to `https://store.cherryaudio.com/galaxy/promotions`. Clicking "Promotions" returns a 403 error.

### Detailed steps to reproduce the issue:

- Enter Nebula
- Enter "Promotions"
- Enter an existing promotions
- Click on a product in a promotion. This page says "Edit Deal"
- Sidebar link back to "Promotions" is wrong there

**Comment by andymnewhouse** [comment]
Whoops loading the wrong layout for that page! It'll be fixed in the next version :)

Fixed in 3.5.26
