### ISSUE TITLE
Creating Deals Improvements

### ISSUE THREAD

**Issue by andymnewhouse** [cherryaudio/store-issues#73]
### Description:

Setting up a promotion containing a lot of products in nebula is super tedious!

I have some suggestions (see image attached):

1.) Add a "+" button to the "Create Deal" page, so multiple products can be added in one go
2.) Add a "Original Price" field between the "Product" and "Price" fields that gets auto-filled and is not editable, for orientation
3.) Add a "Discount" field after the "Price" field. When a new price is entered, the "Discount" field gets auto-updated and vice versa.

![Create Deal](https://user-images.githubusercontent.com/6541180/120711196-b36e2780-c484-11eb-8d60-f58c4d1dbcfb.jpg)

Suggested by Monkey Business Audio

**Comment by tstone** [comment]
The top thing on my list would be being able to see the original price. It requires so much flipping back and forth as it is today to set things up, especially if you haven't memorized the price of everything. 

I also agree, something to make it easier to figure out what % off I'm doing would be a big help. It's not only tedious now to add multiple products, but tedious to figure out if I'm being consistent in my discounting or not.

Another consideration would be if it was possible to actually create a default saved price per module. In this way, when creating modules, I could decide the pricing strategy right then and there, and in the future just add modules to a sale, and use the default price unless I want to go in there and tinker with things. The advantage of this last part would be that it would be easier to run sales consistent throughout the year.

**Comment by andymnewhouse** [comment]
@tstone maybe instead of default sale prices (which I could also do) being able duplicating promotions/sales and all of the subsequent deals

**Comment by tstone** [comment]
I had thought about duplication too. The disadvantage is that you'd have to remember to add new products. The disadvantage of a default sale price is you have to add all products so idk, hah. I imagine that duplicating a promotion is probably easier to implement than adding another column to a DB, so maybe that's a better starting point.

**Comment by Refat2** [comment]
If possible, a grid view option would be nice as well (could have the same options as the current menu). Would take a bit longer to implement though.

**Comment by andymnewhouse** [comment]
@Refat2 do you mean an editable table similar to excel?

**Comment by Refat2** [comment]
Doesnt have to be that advanced, maybe something like this:
A table with all modules and bundles
A toggle button for inclusion or exclusion to the sale
The same options mentioned above (original proce, discount % or discount price)

Would save me at least 15 minutes the three times per year when there is a big sale :)

**Comment by techenby** [comment]
Here's a progress update on this:

The new default view is this, the prices/discounts are not visible until the product is chosen:
<img width="1157" alt="Screen Shot 2021-06-23 at 5 09 18 PM" src="https://user-images.githubusercontent.com/6541180/123174546-e97c4700-d445-11eb-966f-0972f7594b7e.png">

Once a product is chosen, the original price is loaded but disabled:
<img width="1147" alt="Screen Shot 2021-06-23 at 5 09 31 PM" src="https://user-images.githubusercontent.com/6541180/123174673-1c263f80-d446-11eb-8433-0f754ff2e8c4.png">

You can define the discount or the price and the other will reflect the new calculated value based on the original price.
<img width="1146" alt="Screen Shot 2021-06-23 at 5 09 45 PM" src="https://user-images.githubusercontent.com/6541180/123174718-2f390f80-d446-11eb-8678-e5fa49efea79.png">
<img width="1144" alt="Screen Shot 2021-06-23 at 5 09 57 PM" src="https://user-images.githubusercontent.com/6541180/123174763-4546d000-d446-11eb-8646-895bbe173945.png">

Also you can click the "Set as Default" button to set the default sale price for the selected product as the value in the sale price input.

**Comment by techenby** [comment]
Now on to adding multiple deals at once.

**Comment by techenby** [comment]
I think instead of adding a plus button. I'll add a "Save & add Another" button so it'll save the current deal then clear the form so you can add another. Thoughts?

**Comment by Refat2** [comment]
Thats good enough, having the original price and the option of default sale
price will speed things up a lot. Having a grid view would of course speed
things up even more (selecting 30 items one by one in a drop down is not
fast) but the improvements mentioned above are good as is.

**Comment by techenby** [comment]
![Firefox_Screenshot_2021-06-29T20-42-48 931Z](https://user-images.githubusercontent.com/6541180/123864698-ae1fc380-d8f0-11eb-9e86-560acf883dcd.png)

Here's what I started working on for the grid view, but idk if I'll finish now.

**Comment by techenby** [comment]
Fixed in 3.6.4 (minus the grid view)
