### ISSUE TITLE
Nebula Analytics graph is missing

### ISSUE THREAD

**Issue by creart01** [cherryaudio/store-issues#79]
Browser Report: https://www.whatsmybrowser.org/b/_XXXXX_

### Description:
In Nebula Analytics the graph is missing for half a day now...
Incidently I read that Andy did an update to the normal store, maybe related?

**Comment by andymnewhouse** [comment]
This is a duplicate of #78

**Comment by creart01** [comment]
Hadn't seen that...

⁣BlueMail voor Android downloaden ​

Op 9 jun. 2021 16:18, om 16:18, Andy Newhouse ***@***.***> schreef:
