### ISSUE TITLE
Dashboard value not updating?

### ISSUE THREAD

**Issue by creart01** [cherryaudio/store-issues#80]
Browser Report: https://www.whatsmybrowser.org/b/_XXXXX_

### Description:
It seems that the Dashboard 'Gross Sales' value is not updating...
Today modules have been sold - I can check that in Analytics, but they don't show up on the Dashboard...

I did clear the cache and tried several browsers on different machines...

I also checked with Chrome Inspect - that finds errors in the file 'manifest.json'

cheers
Hans

**Comment by techenby** [comment]
Is this still an issue?

**Comment by creart01** [comment]
Can’t really tell at the moment because sales is VERY slow right now…

**Comment by techenby** [comment]
I'm going to close this for now, but feel free to re-open it if it is still an issue.
