### ISSUE TITLE
"Units per Day" shows 1 extra day

### ISSUE THREAD

**Issue by tstone** [cherryaudio/store-issues#81]
Browser Report: https://www.whatsmybrowser.org/b/_XXXXX_

### Description:

This is minor, but I noticed the "Units per Day" chart shows one extra day. Setting the day to 06/15/21 will render the chart to 06/16/21.

**Comment by techenby** [comment]
Yeah I think this is a bug with me converting stuff to PST instead of UTC.

What timezone do you think is most useful? PST since that's where we are, UTC because that's what is stored in the database or converting to your local timezone?

**Comment by scottmetoyer** [comment]
I deployed a set of updates in 3.8.13 that address this and other analytics issues. You can now specify what timezone you want to see results in, as well as accurately scope results down to a single day.

Let me know if everything checks out and I'll go ahead and close this out.
