### ISSUE TITLE
Remove manufacturer showing on bundles choose page

### ISSUE THREAD

**Issue by andymnewhouse** [cherryaudio/store-issues#82]
Browser Report: https://www.whatsmybrowser.org/b/NNVNL

### Description:

Going to a bundle choose page [i.e. for Amplifier](https://store.cherryaudio.com/bundles/choose/core-presets,voltage-core,voltage-modular-core,voltage-modular-ignite,voltage-modular-nucleus?ref=amplifier) the Remove Manufacturer is shown immediately and shows 500 error when trying to cancel or remove.

### Detailed steps to reproduce the issue:

1. Go To https://store.cherryaudio.com/bundles/choose/core-presets,voltage-core,voltage-modular-core,voltage-modular-ignite,voltage-modular-nucleus?ref=amplifier
2. See modal
3. Click cancel
4. See 500 error

**Comment by techenby** [comment]
Fixed in 3.6.4
