### ISSUE TITLE
All or None category options.

### ISSUE THREAD

**Issue by gregbir** [cherryaudio/store-issues#83]
Browser Report: https://www.whatsmybrowser.org/b/7M5I4

### Description:
All/None doesn't work properly for categories

### Detailed steps to reproduce the issue:
1. Choose categories on the left.
2. Select None.
3. Select All.
4. Not all items are selected, and you have to manually fill in the checkboxes or navigate away and come back.

**Comment by cmountvpr** [comment]
Love you guys, but it's been a month since this bug was posted, and it persists. And the temporary fix, to turn them all on one at a time, has its own bug - turning one on sometimes turns another one off.

**Comment by techenby** [comment]
Fixed in 3.6.5
