### ISSUE TITLE
Transfer license - Get 500 error

### ISSUE THREAD

**Issue by Pcs800** [cherryaudio/store-issues#88]
Browser Report:  _https://www.whatsmybrowser.org/b/R3NUS

### Detailed steps to reproduce the issue:
I transferred a memorymode license from one email to another and got a 500 error.
Realizing the user typed a space before "com", I have corrected the issue, but thought you would want to know of the error in this particular scenario.

**Comment by techenby** [comment]
Fixed in 3.6.7
