### ISSUE TITLE
Email Notification of Module Submission Status Changes

### ISSUE THREAD

**Issue by TheAndyMac** [cherryaudio/store-issues#90]
### Description:
In the old dashboard, status changes (approved, etc.) were done by email. In the new dashboard you have to check manually on the status page. It would be really helpful if a developer could "subscribe" to their submission status changes, so that they get an email to say that one or more statuses have changed - this could be a summary (or simple notification of "some changes") generated either on change, or on a regular basis (every hour/every eight hours/every day...) with a link to their status page.

**Comment by techenby** [comment]
Fixed in 3.7.1
