### ISSUE TITLE
Changes to Upgrade Option Prices does not allow save

### ISSUE THREAD

**Issue by TheAndyMac** [cherryaudio/store-issues#92]
Browser Report:  https://www.whatsmybrowser.org/b/LZXEF

### Description:
If I make a change to a price in the Upgrade Options for a module/bundle, the save option does not recognise that something has been changed (no marker) and does not allow a save. Have to add and delete a row to force it to see the change.

### Detailed steps to reproduce the issue:
Existing module or bundle with some Upgrade prices. Change price of one of the Upgrade options. Indicator for change does NOT appear. Save button shows N/A indicator.

Workaround: add new row (with default values) and delete row. Indicator now shows and Save button works.

**Comment by techenby** [comment]
I believe at some point I fixed this but didn't update this issue. When you get a second, can you verify this is working for you?

Thanks!

**Comment by TheAndyMac** [comment]
Hi Andy
Will do - probably will be sometime over the weekend if that's ok.
I've not had a chance to test the beta library stuff yet, but as soon as I do that, I'll confirm all good as well.
Regards
Andrew Macaulay

**Comment by techenby** [comment]
Thank you! Anytime you can would be great, I really appreciate it :)

**Comment by TheAndyMac** [comment]
Tested and working now - thank you :-)
