### ISSUE TITLE
Promotions With Conditions Fail with Error 500

### ISSUE THREAD

**Issue by TheAndyMac** [cherryaudio/store-issues#93]
Browser Report:  https://www.whatsmybrowser.org/b/LZXEF

### Description:
Setting up or editing Promotions. Adding individual items without conditions works. Switch on "Conditions" and page overlay with Error 500 comes up. Also, if try to edit existing promotion with conditions, also comes up with Error 500. Only workaround was to go back to the old dashboard to setup the Promotion.

### Detailed steps to reproduce the issue:
1. Setup new promotion. Add new sale price. Switch on Conditions - Error 500 comes up.
2. Open existing promotion with some condition-based pricing. Select to edit - Error 500 comes up.

**Comment by techenby** [comment]
Fixed in 3.6.8
