### ISSUE TITLE
Capability Create New Promotion BASED ON a Previous Promotion

### ISSUE THREAD

**Issue by TheAndyMac** [cherryaudio/store-issues#94]
### Description:
On the Promotions screen, provide the option to create a new promotion by COPYING a previous one, picking up all the sale pricing details as a starter and just needing the title and dates to be completed - and then anything else edited as needed.

**Comment by techenby** [comment]
Will be in the next release, if the original sale's name was "Winter Sale" the new name will be "Copy of Winter Sale". I've also defaulted the dates to start to the next day and end 15 days from the current day.

All deals are copied as well.

**Comment by TheAndyMac** [comment]
Thanks – that will save us all quite a lot of time when setting them up 😊

Regards
Andrew Macaulay

**Comment by techenby** [comment]
Fixed in 3.6.8
