### ISSUE TITLE
Promotion - Add Many Items does not have a Save Button

### ISSUE THREAD

**Issue by TheAndyMac** [cherryaudio/store-issues#95]
Browser Report:  https://www.whatsmybrowser.org/b/LZXEF

### Description:
Tried using the Add Many Items but having entered some details, no Save button was showing :-(

### Detailed steps to reproduce the issue:
Create new promotion (or use existing one).
Press the Add Many button
Select some items and add pricing
NO SAVE OPTION shows and does not see any way to save them

**Comment by techenby** [comment]
Whoops! I'll get to all these today, and hopefully publish the fix today or tomorrow.

**Comment by TheAndyMac** [comment]
👍

Regards
Andrew Macaulay

________________________________

**Comment by techenby** [comment]
Looking at this again, this is missing a few key things not just a save button. So for now I'm going to remove this feature. Instead please use the "Add another" button when creating deals.

The interface how it is now would not allow you to add conditions and have multiple configurations for a product. Or maybe that's not necessary for this? What do you think?

**Comment by TheAndyMac** [comment]
I think a simple "add multiple" as a way to a bulk setup would potentially still be useful - especially if there a way to do a bulk setting across them all (especially a % discount), but maybe also have some text on the header (and maybe a tooltip on the button) to explain what it is aimed to do - telling the user that it can't do conditions or multiple configurations for a product - and to do that level of editing they will have to edit/add additional ones after the "bulk" process. Maybe call it something different rather than "Add Many"?

Regards
Andrew Macaulay

**Comment by techenby** [comment]
Fixed in 3.6.8
