### ISSUE TITLE
500 Error selection all products on Products Page

### ISSUE THREAD

**Issue by SynthDan** [cherryaudio/store-issues#96]
I discovered this with the following steps:

1. Select Cherry Audio / MRB Manufacturer
2. Search for VM900 (brings up around 20+ results)
3. Click the top checkbox (to the left of NAME) to select all products.

..but it turns out you can just click on Products and select that checkbox. You'll always get a 500 | SERVER ERROR message.

**Comment by techenby** [comment]
Fixed in 3.6.9
