### ISSUE TITLE
All option in filter for modules/bundles/presets doesn't save

### ISSUE THREAD

**Issue by gregbir** [cherryaudio/store-issues#99]
If you filter for an item, that gets saved, but filtering for All doesn't get saved, so when you come back to the page, there are a seemingly random collection of modules or bundles or whatever selected. Multiple customers have reported this.

![storemanufacturers](https://user-images.githubusercontent.com/86313096/140419409-5be5bfe7-10a2-43c8-a3da-c01ad41eb246.png)

**Comment by techenby** [comment]
Fixed in 3.7.1
